package sinolight.cn.qgapp.data.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sinolight.cn.qgapp.data.bean.Account;
import sinolight.cn.qgapp.data.bean.SearchData;

import sinolight.cn.qgapp.data.db.AccountDao;
import sinolight.cn.qgapp.data.db.SearchDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig searchDataDaoConfig;

    private final AccountDao accountDao;
    private final SearchDataDao searchDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        searchDataDaoConfig = daoConfigMap.get(SearchDataDao.class).clone();
        searchDataDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        searchDataDao = new SearchDataDao(searchDataDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(SearchData.class, searchDataDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        searchDataDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public SearchDataDao getSearchDataDao() {
        return searchDataDao;
    }

}
